dist: focal  # Ubuntu 20.04 LTS
sudo: required
language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - cmake
            - cmake-data
            - lcov
            - build-essential
            - libgtk2.0-dev 
            - pkg-config 
            - libavcodec-dev 
            - libavformat-dev 
            - libswscale-dev
            - python3-dev 
            - python3-numpy 
            - libtbb2 
            - libtbb-dev 
            - libjpeg-dev 
            - libpng-dev 
            - libtiff-dev 
            - libdc1394-22-dev
      env: 
        - COMPILER=g++-9
        - OPENCV_VERSION=3.4.5

before_install:
  - pip install --user cpp-coveralls

install:
  # OpenCV installation
  - git clone --branch ${OPENCV_VERSION} --depth 1 https://github.com/opencv/opencv.git
  - git clone --branch ${OPENCV_VERSION} --depth 1 https://github.com/opencv/opencv_contrib.git
  - cd opencv
  - mkdir build
  - cd build
  - cmake -D CMAKE_BUILD_TYPE=RELEASE 
          -D BUILD_EXAMPLES=OFF 
          -D BUILD_opencv_apps=OFF 
          -D BUILD_DOCS=OFF 
          -D BUILD_PERF_TESTS=OFF 
          -D BUILD_TESTS=OFF 
          -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules 
          -D CMAKE_INSTALL_PREFIX=/usr/local 
          -D ENABLE_FAST_MATH=ON 
          -D WITH_TBB=ON 
          ..
  - make -j$(nproc)
  - sudo make install
  - sudo ldconfig
  - cd ../..
  
  # Download YOLO weights
  - cd models
  - wget --no-check-certificate https://pjreddie.com/media/files/yolov3.weights
  - cd ..

script:
  - export CXX=$COMPILER
  - mkdir build
  - cd build
  - cmake -DCOVERAGE=ON -DCMAKE_BUILD_TYPE=Debug ../
  - make -j$(nproc)
  - test/cpp-test

after_success:
  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

notifications:
  email: false

cache:
  directories:
    - opencv/build
    - opencv_contrib
